#import "../gql/fragments/Image.gql"
#import "../gql/fragments/MediaAsset.gql"

#import "../gql/fragments/BlockAssociatedTopicCardsFragment.gql"
#import "../gql/fragments/BlockCallToActionFragment.gql"
#import "../gql/fragments/BlockContactInfoFragment.gql"
#import "../gql/fragments/BlockFormFragment.gql"
#import "../gql/fragments/BlockHorizontalDividerFragment.gql"
#import "../gql/fragments/BlockInfoFragment.gql"
#import "../gql/fragments/BlockImpactNumberCardsFragment.gql"
#import "../gql/fragments/BlockMediaGalleryFragment.gql"
#import "../gql/fragments/BlockMediaWithTextFragment.gql"
#import "../gql/fragments/BlockPullQuoteFragment.gql"
#import "../gql/fragments/BlockRichTextFragment.gql"
#import "../gql/fragments/BlockSimpleCardsFragment.gql"

fragment AllFtvaFpb on ElementInterface {
    blocks: allFtvaFpb {
        id
        typeHandle

        ... on allFpb_associatedTopicCards_BlockType {
            ...BlockAssociatedTopicCardsFragment
        }
        ... on allFtvaFpb_callToAction_BlockType {
            ...BlockCallToActionFragment
        }
        ... on allFtvaFpb_contactInfo_BlockType {
            ...BlockContactInfoFragment
        }
        ... on allFtvaFpb_form_BlockType {
            ...BlockFormFragment
        }
        ... on allFtvaFpb_horizontalDivider_BlockType {
            ...BlockHorizontalDividerFragment
        }
        ... on allFtvaFpb_infoBlock_BlockType {
            ...BlockInfoFragment
        }
        ... on allFtvaFpb_impactNumberCards_BlockType {
            ...BlockImpactNumberCardsFragment
        }
        ... on allFtvaFpb_mediaGallery_BlockType {
            ...BlockMediaGalleryFragment
        }
        ... on allFtvaFpb_mediaWithText_BlockType {
            ...BlockMediaWithTextFragment
        }
        ... on allFtvaFpb_pullQuote_BlockType {
            ...BlockPullQuoteFragment
        }
        ... on allFtvaFpb_richText_BlockType {
            ...BlockRichTextFragment
        }
        ...on allFtvaFpb_simpleCards_BlockType {
            ...BlockSimpleCardsFragment
        }
    }
}
