allowBuilds:
  '@parcel/watcher': true
  cypress: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
engineStrict: true
minimumReleaseAgeExclude:
  - '@ucla-library-monorepo/ucla-library-website-components@1.84.1'
  - '@ucla-library/component-library-nuxt-module@1.4.8'
