fragment BlockHorizontalDividerFragment on ElementInterface {
    id
    typeHandle
    BlockHorizontalDivider {
        ... on horizontalDivider_horizontalDivider_BlockType {
            id
        }
    }
}
