fragment BlockContactInfoFragment on ElementInterface {
    id
    typeHandle
    BlockContactInfo {
        ... on contactInfo_contactInfo_BlockType {
            id
            title
        }
    }
}
