fragment BlockAssociatedTopicCardsFragment on ElementInterface {
  typeHandle
  sectionTitle: titleGeneral
  sectionSummary: summary
  associatedTopicsFlexiblePageBlock {
    ... on associatedTopicsFlexiblePageBlock_associatedTopics_BlockType {
      topics {
        typeHandle
        title
        externalResourceUrl
        uri
        text: summary
      }
    }
  }
}
