fragment BlockHorizontalDividerFragment on ElementInterface {
    id
    typeHandle
    horizontalDivider {
        ... on horizontalDivider_horizontalDivider_BlockType {
            id
            typeHandle
            horizontalDivider
        }
    }
}
