fragment BlockCardWithImageFragment on ElementInterface {
  id
  typeHandle
  sectionTitle: titleGeneral
  sectionSummary: summary
  cardWithImage: ftvaFlexiblePageBlock_cardWithImage {
    id
    ... on ftvaFlexiblePageBlock_cardWithImage_internalContent_BlockType {
      id
      typeHandle
      sectionHandle
      contentLink {
        id
        typeHandle
        sectionHandle
        contentType: sectionHandle
        uri
        slug
        ftvaImage {
          ...Image
        }
        image {
          ...Image
        }
        imageCarousel {
          ... on imageCarousel_imageCarousel_BlockType {
            image {
              ...Image
            }
            altText
          }
        }
        heroImage {
          ... on heroImage_heroImage_BlockType {
            image {
              ...Image
            }
            altText
          }
        }
        title
        eventTitle
        titleGeneral
        formattedTitle
        startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        endDateWithTime @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        startDate @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        endDate @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        postDate @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        ongoing
      }
    }
    ... on ftvaFlexiblePageBlock_cardWithImage_externalContent_BlockType {
      id
      typeHandle
      sectionHandle
      titleGeneral
      image {
        ...Image
      }
      to: externalLink
    }

  }
}
