fragment BlockCardWithImageFragment on ElementInterface {
  id
  typeHandle
  sectionTitle: titleGeneral
  sectionSummary: summary
  ftvaFlexiblePageBlock_cardWithImage {
    id
    ... on ftvaFlexiblePageBlock_cardWithImage_internalContent_BlockType {
      id
      typeHandle
      contentLink {
        id
        contentType: sectionHandle
        to: uri
        title
        text: summary
        eventDescription
        projectCategory: format
        articleCategory: articleCategories {
          title
        }
        articleByline1: staffMember {
          id
          to: uri
          title
        }
        articleByline2: postDate
        ongoing
        startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        endDateWithTime @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        startDate @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        endDate @formatDateTime(format: "Y-m-d\\TH:i", timezone: "America/Los_Angeles")
        eventType {
          ... on eventType_Category {
            id
            title
          }
        }
        associatedLocations {
          id
          title
          to: uri
        }
        heroImage {
          ... on heroImage_heroImage_BlockType {
            id
            image {
              ...Image
            }
            altText
          }
        }
      }
    }
    ... on ftvaFlexiblePageBlock_cardWithImage_externalContent_BlockType {
      id
      typeHandle
      title: titleGeneral
      image {
        ...Image
      }
      byline1
      byline2
      category
      text: summary
      to: externalLink
    }
  }
}
