fragment BlockInfoFragment on ElementInterface {
  id
  typeHandle
  sectionTitle: titleGeneral
  sectionSummary: summary
  infoBlock {
    ... on infoBlock_infoBlock_BlockType {
      typeHandle
      icon
      heading
      text
    }
    ... on infoBlock_contactInfoBlock_BlockType {
      typeHandle
      email
      phone
      address
    }
  }
}
