#import "../gql/fragments/Image.gql"
#import "../gql/fragments/collections/DefaultFpbWithCardsAndHighlight.gql"
#import "../gql/fragments/collections/ExhibitionsAndCollectionsFpb.gql"

query FTVADetail($slug: [String!]) {
  entry(section: "ftvaEvent", slug: $slug) {
    id
    typeHandle
    sectionHandle
    uri
    eventTitle
    ... on ftvaEvent_ftvaEvent_Entry {
      id
      imageCarousel {
        ... on imageCarousel_imageCarousel_BlockType {
          id
          image {
            ...Image
          }
          creditText
        }
      }

      ftvaEventFilters {
        title
      }
      ftvaEventIntroduction
      eventDescription

      # acknowledements: richText
      richText
      guestSpeaker


      # BlockEventDetail
      startDate: startDateWithTime @formatDateTime(format: "Y-m-d", timezone: "America/Los_Angeles")
      startTime: startDateWithTime @formatDateTime(format: "TH:i:s", timezone: "America/Los_Angeles")
      location {
        title
        uri
      }

      # BlockInfo
      ftvaTicketInformation {
        id
        title
        uri
      }

      # Ticket Info
      ftvaEventFilters {
        title
        uri
      }

      ftvaEventScreeningDetails {
        ... on ftvaEventScreeningDetails_screeningDetails_BlockType {
          id
          screeningTitle
          alternateTitle
          year
          country
          languageTranslated
          languageInfo
          runtime
          screeningTags {
            title
          }
          descriptionOfScreening
          trailer
          typeHandle
        }
      }
    }

    ... on ftvaEvent_ftvaEvent_Entry {
      ftvaEventRegistration {
        ... on ftvaEventRegistration_eventRegistration_BlockType {
          registrationText
          registrationUrlLink
        }
      }
    }
  }

  categorySeries: entry(
    section: "ftvaEventSeries"
    relatedToEntries: {section: "ftvaEvent", slug: $slug}) {
    ... on ftvaEventSeries_eventSeries_Entry {
      id
      ftvaEvent {
        ... on ftvaEvent_ftvaEvent_Entry {
        id
        title
        startDate: startDateWithTime @formatDateTime(format: "Y-m-d", timezone: "America/Los_Angeles")
        startTime: startDateWithTime @formatDateTime(format: "TH:i:s", timezone: "America/Los_Angeles")

          ftvaImage {
            ...Image
          }
        }
      }
    }
  }
}

fragment Image on AssetInterface {
  id
  src: url(transform: "fullscreen")
  height(transform: "fullscreen")
  width(transform: "fullscreen")
  srcset(sizes: ["375", "960", "1280", "1920", "2560"])
  alt: altText
  focalPoint
}
