#import "../gql/fragments/collections/AllFtvaFpb.gql"

query FTVAGeneralContent($slug: [String!]) {
  entry(section: "ftvaGeneralContentPage", slug: $slug) {
    ... on ftvaGeneralContentPage_generalContentPage_Entry {
      id
      uri
      slug
      title
      formattedTitle
      ftvaHomepageDescription
      ...AllFtvaFpb
    }
  }
}

# Because we gencontent page uses ftva/ in the uri to differentiate between the lib and meat websites the GQL query will need the slug instead of the uri
