query FTVACollectionLayoutType($slug: [String!]) {
  ftvaCollection: entry(section: "ftvaCollection", slug: $slug) {
    id
    ftvaCollectionLayoutType
    title
    postDate
    ftvaHomepageDescription
    ftvaFilters
    sectionHandle
    ftvaCollectionType
    richText
  }
}
