#import "../gql/fragments/Image.gql"

query FTVACollectionDetail($slug: [String!]) {
  ftvaCollection: entry(section: "ftvaCollection", slug: $slug) {
    id
    typeHandle
    sectionHandle
    postDate
    imageCarousel {
      ... on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }
    title
    sectionTitle
    ftvaCollectionType
    ftvaHomepageDescription
    richText
    videoEmbed
    viewAllSectionLink {
      ... on viewAllSectionLink_viewAllSection_BlockType {
        viewAllText
        viewAllLink {
          uri
        }
      }
    }
    infoBlock {
      ... on infoBlock_infoBlock_BlockType {
        icon
        text
      }
    }
    heroimage: ftvaHeroImage {
     ...Image
    }
    ftvaRelatedCollections {
      ftvaImage {
        ...Image
      }
      imageCarousel {
        ... on imageCarousel_imageCarousel_BlockType {
          image {
            ...Image
          }
          creditText
        }
      }
      title
      richText
      uri
    }
    uri
    slug
    to: uri
  }
}
