#import "../gql/fragments/Image.gql"

query FTVAHomepage {
  entry(section: ["ftvaHomepage"]) {
    id
    title
    ... on ftvaHomepage_ftvaHomepage_Entry {
      id
      summary
      sectionTitle
      richTextSimplified
      ftvaRelatedResources
      visitAndLearnSectionTitle
      ftvaQuickLinks {
        ... on ftvaQuickLinks_quickLink_BlockType {
          titleGeneral
          id
          description
          urlLink
          image {
            ...Image
          }
        }
      }
      ftvaFeaturedEventsSection {
        ... on ftvaFeaturedEventsSection_featuredEventsSection_BlockType {
        id
        sectionTitle
        seeAllText
        featuredEvents {
         ... on ftvaEvent_ftvaEvent_Entry {
          id
          sectionHandle
          uri
          workshopOrEventSeriesType
          title
          eventTitle
          startDateWithTime
              @formatDateTime(
                  format: "Y-m-d\\TH:i"
                  timezone: "America/Los_Angeles"
              )
          endDateWithTime
              @formatDateTime(
                  format: "Y-m-d\\TH:i"
                  timezone: "America/Los_Angeles"
              )
          uri
          ftvaImage {
            ...Image
          }
          imageCarousel {
            ... on imageCarousel_imageCarousel_BlockType {
              image {
                ...Image
              }
            }
          }
        }
        }
        }
      }
      ftvaFeaturedEntries {
        id
        typeHandle
        uri
        title
        ftvaHomepageTitle
        ftvaHomepageDescription
        imageCarousel {
            ... on imageCarousel_imageCarousel_BlockType {
              image {
                ...Image
              }
            }
          }
        # FOR EVENT SERIES
        startDate
        endDate
        ongoing
				# FOR EVENT
      	startDateWithTime
        ftvaImage {
          ...Image
        }
      }
      ftvaFeaturedCollectionsSectionSingle {
        ... on ftvaFeaturedCollectionsSectionSingle_featuredCollections_BlockType {
          id
          sectionTitle
          sectionDescription
          seeAllText
          seeAllLink
          featuredCollections {
            id
            title
            uri
            ftvaImage {
              ...Image
            }
            imageCarousel {
              ... on imageCarousel_imageCarousel_BlockType {
                image {
                  ...Image
                }
                altText
              }
            }
          }
        }
      }
      ftvaFeaturedArticlesSection {
        ... on ftvaFeaturedArticlesSection_ftvaFeaturedArticlesSection_BlockType {
          seeAllText
          sectionTitle
          featuredArticles {
            id
            title
            uri
            ftvaHomepageDescription
            ftvaImage {
              ...Image
            }
            imageCarousel {
              ... on imageCarousel_imageCarousel_BlockType {
                image {
                  ...Image
                }
                altText
              }
            }
          }
        }
      }
      beforeAfterImageCarousel {
        ... on beforeAfterImageCarousel_imageCarousel_BlockType {
          beforeImage {
            ... on mediaAndDocuments_Asset {
              id
              src: url
              altText
              focalPoint
              height
              width
              srcset(sizes: ["375", "960", "1280", "1920", "2560"])
            }
          }
          afterImage {
            ... on mediaAndDocuments_Asset {
              id
              src: url
              altText
              focalPoint
              height
              width
              srcset(sizes: ["375", "960", "1280", "1920", "2560"])
            }
          }
          caption
        }
      }
    }
  }
}
