#import "../gql/fragments/Image.gql"


query FTVAArticleDetail($slug: [String!]) {
  ftvaArticle: entry(section: "ftvaArticle", slug: $slug)  {
    id
    typeHandle
    sectionHandle
    postDate
    slug
    title
    uri

    image: ftvaImage {
      ...Image
    }

    imageCarousel {
      ... on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }

    # CardMeta
    articleCategories {
      title
    }
    contributors {
      ... on contributors_externalContributor_BlockType {
        byline
        contributor
      }
      externalContributor {
        id
        byline
        contributor
      }
    }
    aboutTheAuthor

    # FTVA Flexible Page Block Collection (FPBs)

  }
  # SectionTeaserCard (Recent posts)
  # page only displays 3 but we query 4 in case the list includes the current article
  ftvaRecentPosts: entries( section: "ftvaArticle", limit: 4, orderBy: "postDate ASC") {
    id
    title
    to: slug
    articleCategories {
      title
    }
    imageCarousel {
      ... on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
      }
    }
    postDate @formatDateTime(format: "mm d, Y", timezone: "America/Los_Angeles")
  }
}
