# options "ftvaCollectionListingLARebellion"
query FTVACollectionFilmography($section: [String!]) {
 entry(section:$section) {
  id
  title: titleGeneral
  postDate
  ftvaHomepageDescription: summary
  ftvaFilters
  sectionHandle
 }
}
