#import "../gql/fragments/Image.gql"

query FTVALARebellionFilmmakersDetail($slug: [String!]) {
  ftvaLARebellionIndividual: entry(section: "ftvaLARebellionIndividual", slug: $slug) {
    id
    title
    typeHandle
    sectionHandle
    postDate
    slug
    uri
    to: uri
    richText
    nameFirst
    nameLast

    image: ftvaImage {
      ...Image
    }

    imageCarousel {
      ...on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }

    associatedFilms {
      ... on associatedFilms_film_BlockType {
        image {
          ...Image
        }
      }
      titleGeneral
      description
      roles
      year
      filmLink {
        uri
        slug
      }
    }

  }
}
