#import "~/gql/fragments/MenuItem.gql"

query FTVAFooterPrimaryItems {
    nodes(navHandle: "ftvaPrimaryMenu", level: 1) {
        ...MenuItem
        children {
            ...MenuItem
        }
    }
}
