#import "../gql/fragments/Image.gql"

query FTVAEventSeriesList {
  entries(section: ["ftvaEventSeries"], orderBy: "postDate") {
    typeHandle
    id
    title
    to: uri
    ... on ftvaEventSeries_eventSeries_Entry {
      id
      eventDescription
      image: ftvaImage {
        ...Image
      }
      startDate @formatDateTime(format: "Y-m-d", timezone: "America/Los_Angeles")
      endDate @formatDateTime(format: "Y-m-d", timezone: "America/Los_Angeles")
    }
  }
}
