#import "../gql/fragments/Image.gql"

query FTVAEventDetail($slug: [String!]) {
  ftvaEvent: entry(section: "ftvaEvent", slug: $slug) {
    id
    typeHandle
    slug
    uri

    imageCarousel {
      ...on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }

    # CardMeta
    title: eventTitle
    guestSpeaker
    tagLabels: ftvaEventFilters {
      title
      uri
    }
    introduction: ftvaEventIntroduction

    eventDescription
    acknowledements: richText

    ftvaEventScreeningDetails {
      ...on ftvaEventScreeningDetails_screeningDetails_BlockType {
        title: screeningTitle
        alternateTitle
        language: languageTranslated
        year
        country
        languageInfo
        runtime
        tagLabels: screeningTags {
          title
        }
        text: descriptionOfScreening
        trailer
        image {
          ...on mediaAndDocuments_Asset {
            ...Image
          }
        }
      }
    }

    # SIDEBAR
    # BlockEventDetail
    startDateWithTime
      @formatDateTime(
        format: "Y-m-d\\TH:i"
        timezone: "America/Los_Angeles"
      )
    startDate: startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
    startTime: startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
    location {
      title
      campusMapId
      publicUrl
      address
    }

    # BlockInfo / Ticket Info
    ftvaTicketInformation {
      title
      uri
    }
    ftvaEventRegistration {
      ...on ftvaEventRegistration_eventRegistration_BlockType {
        registrationText
        registrationUrlLink
      }
    }
  }

  # SectionTeaserCard
  ftvaEventSeries: entries(
    section: "ftvaEventSeries",  orderBy: "postDate",
    relatedToEntries: {section: "ftvaEvent", slug: $slug}) {
    ... on ftvaEventSeries_eventSeries_Entry {
      id
      to: uri
      slug
      typeHandle
      title
      ftvaEvent(startDateWithTime: ">= now") {
        ... on ftvaEvent_ftvaEvent_Entry {
          id
          to: slug
          title: eventTitle
          startDate: startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
          startTime: startDateWithTime @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
          image: ftvaImage {
            ...Image
          }
        }
      }
    }
  }
}
