#import "../gql/fragments/Image.gql"

query FTVAArticleList($slug: [String!]) {
  entry(section: ["ftvaListingArticles"], slug: $slug) {
    id
    typeHandle
    sectionHandle
    title: titleGeneral
    summary
    displaySummary
    ftvaFeaturedArticles {
      title
      ftvaAlternativeTitle
      postDate
      articleCategories {
        title
      }
      ftvaHomepageDescription
      uri
      image: ftvaImage {
        ...Image
      }
    }
  }
}

