#import "../gql/fragments/Image.gql"
#import "../gql/fragments/MediaAsset.gql"
#import "../gql/fragments/collections/AllFtvaFpb.gql"

query FTVAArticleDetail($slug: [String!]) {
  ftvaArticle: entry(section: "ftvaArticle", slug: $slug)  {
    id
    typeHandle
    postDate
    title
    slug
    uri

    imageCarousel {
      ... on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }

    # CardMeta
    articleCategories {
      title
    }
    contributors {
      ... on contributors_externalContributor_BlockType {
        byline
        contributor
      }
      externalContributor {
        id
        byline
        contributor
      }
    }
    aboutTheAuthor

    # SectionTeaserCard (Recent posts)


    # Flexible Page Block Collection (FPBs)
    ...AllFpb
  }
}
