# import "../gql/fragments/Image.gql"

# TODO remove some of these fields?
query FTVACollectionList {
  entries(section: ["ftvaCollectionStory","ftvaCollection"], orderBy: "postDate") {
    typeHandle
    sectionHandle
    uri
    id
    title
    slug
    to: uri
    ftvaHomepageTitle
    ftvaHomepageDescription
    ftvaCollectionType
    richText
    infoBlock {
      ... on infoBlock_infoBlock_BlockType {
        icon
        text
      }
    }
    # unknown fragment errors for some reason, works in craftcms
    # seems to be happening on all list pages?
    # ftvaImage {
    #   ...Image
    # }



    ftvaRelatedCollections {
      title
      richText
      uri
    }
  }
}
