#import "../gql/fragments/Image.gql"

query FTVADetailSeries($slug: [String!]) {
  entry(
    section: "ftvaEventSeries"
    relatedToEntries: {section: "ftvaEvent", slug: $slug}) {
    ... on ftvaEventSeries_eventSeries_Entry {
      id
      ftvaEvent {
        ... on ftvaEvent_ftvaEvent_Entry {
        id
        title
        startDate: startDateWithTime @formatDateTime(format: "Y-m-d", timezone: "America/Los_Angeles")
        startTime: startDateWithTime @formatDateTime(format: "TH:i:s", timezone: "America/Los_Angeles")

          ftvaImage {
            ...Image
          }
        }
      }
    }
  }
}
