# import "../gql/fragments/Image.gql"

# TODO remove some of these fields? 
query FTVACollectionList {
  entries(section: ["ftvaCollection"], orderBy: "postDate") {
    typeHandle
    id
    title
    sectionTitle
    slug
    to: uri
    ftvaHomepageTitle
    ftvaHomepageDescription
    ftvaCollectionType
    richText 
    videoEmbed
    viewAllSectionLink
    infoBlock 
    # no images on listview?
    # heroimage: ftvaHeroImage {
    #  ...Image
    # }
    # image: ftvaImage {
    #  ...Image
    # }

    ftvaRelatedCollections {
      title
      uri
    }
  }
}