#import "../gql/fragments/Image.gql"

query FTVACollectionDetail($slug: [String!]) {
  ftvaCollection: entry(section: "ftvaCollection", slug: $slug) {
    typeHandle
    id
    title
    sectionTitle
    slug
    to: uri
    ftvaHomepageTitle
    ftvaHomepageDescription
    ftvaCollectionType
    richText 
    videoEmbed
    viewAllSectionLink
    infoBlock 
    heroimage: ftvaHeroImage {
     ...Image
    }
    # image: ftvaImage {
    #  ...Image
    # }

    # ftvaRelatedCollections {
    #   title
    #   uri
    # }
  }
}
