#import "../gql/fragments/Image.gql"

query FTVACollectionsListing($section: [String!]) {
  entry(section: $section) {
    id
    slug
    uri
    sectionHandle
    postDate
    title: titleGeneral
    summary
    displaySummary
    sectionHeader {
      sectionTitle
      sectionSummary
    }
    associatedGeneralContentPagesFtva {
      id
      title
      slug
      uri
      ftvaImage {
        ...Image
      }
      imageCarousel {
        ... on imageCarousel_imageCarousel_BlockType {
          image {
            ...Image
          }
        }
      }
    }
  }
}
