#import "../gql/fragments/collections/AllFtvaFpb.gql"
#import "../gql/fragments/Image.gql"


query FTVACollectionStory($slug: [String!]){
  entry(section: "ftvaCollectionStory", slug:$slug) {
    id
    slug
    uri
    sectionHandle
    title
    summary
    ftvaImage {
      ...Image
    }
    imageCarousel {
      ... on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }
    ftvaAdditionalResources {
      id
      title
      slug
      uri
      ftvaImage {
        ...Image
      }
      imageCarousel {
        ... on imageCarousel_imageCarousel_BlockType {
          image {
            ...Image
          }
        }
      }
    }
    ...AllFtvaFpb
  }
}
