# import "../gql/fragments/Image.gql"
# typeHandle ftvaListingArticles

query FTVAArticleList {
  entries(section: ["ftvaListingArticle"], orderBy: "postDate") {
    typeHandle
    id
    title
    to: uri
    text: summary
    # image
  }
}
