#import "../gql/fragments/Image.gql"

query FTVAEventSeriesList {
  entries(section: ["ftvaEventSeries"], orderBy: "postDate DESC") {
    id
    typeHandle
    sectionHandle
    title

    ... on ftvaEventSeries_eventSeries_Entry {
      to: uri
      description: eventDescription
      image: ftvaImage {
       ...Image
      }
      startDate @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
      endDate @formatDateTime(format: "Y-m-d\\TH:i:s", timezone: "America/Los_Angeles")
      ongoing
    }
  }
}
