#import "../gql/fragments/Image.gql"
#import "../gql/fragments/collections/AllFtvaFpb.gql"

query FTVAGeneralContent($path: [String!]) {
  entry(section: "ftvaGeneralContentPage") {
    id
    uri
    title
    formattedTitle
    text: ftvaHomepageDescription
    imageCarousel {
      ...on imageCarousel_imageCarousel_BlockType {
        image {
          ...Image
        }
        creditText
      }
    }
    ...AllFtvaFpb
  }
}
