query Globals {
    globalSets {
        dataId: id
        handle

        ... on ftvaViewingInformation_GlobalSet {
              handle
              title: titleGeneral
              text: richTextSimplified
            }
    }
}
