name: Submit screenshots to Percy for visual regression testing.

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  percy:
    name: Percy - Nuxt3.x Site
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      # Checkout once (composite no longer checks out)
      - uses: actions/checkout@v4

      # Workspace setup: Node 18, pnpm 9.12.1, caches, install deps
      - uses: ./.github/workflows/setup-workspace

      # Cache prerendered static site
      - name: Cache built static site
        id: cache-nuxt3
        uses: actions/cache@v3
        with:
          path: .output/public
          key: nuxt3-site-${{ github.sha }}

      # ES alias per branch
      - name: Set env vars for PR preview
        if: github.ref_name != 'main'
        run: echo "ES_ALIAS=${{secrets.ES_ALIAS_TEST}}-percy-tests-${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

      - name: Set env vars for main
        if: github.ref_name == 'main'
        run: echo "ES_ALIAS=${{secrets.ES_ALIAS_TEST}}" >> $GITHUB_ENV

      # Generate only on cache miss
      - name: Generate site
        if: steps.cache-nuxt3.outputs.cache-hit != 'true'
        run: pnpm run generate
        env:
          CRAFT_ENDPOINT: ${{ secrets.CRAFT_ENDPOINT_TEST }}
          S3_BUCKET: "https://static.library.ucla.edu/"
          ES_URL: ${{ secrets.ES_URL }}
          ESApiKey: ${{ secrets.ESApiKey }}
          ES_READ_KEY: ${{ secrets.ES_READ_KEY_TEST }}
          ES_WRITE_KEY: ${{ secrets.ES_WRITE_KEY_TEST }}
          ES_ALIAS: ${{ env.ES_ALIAS }}
          ES_INDEX_PREFIX: ${{ secrets.ES_INDEX_PREFIX_TEST }}

      # Optional: cache Cypress binary for speed
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-15
      # Add a quick debug echo just before the action
      - name: Debug NODE_OPTIONS
        run: |
          echo "Top-level NODE_OPTIONS='${NODE_OPTIONS}'"
          node -p "process.execArgv"

      # Run Percy + Cypress. Use local @percy/cli (devDep). Clear NODE_OPTIONS.
      - uses: cypress-io/github-action@v5
        with:
          start: pnpm dlx serve .output/public
          wait-on: http://localhost:3000
          wait-on-timeout: 110
          install: false
          # Use a shell so we can unset for the whole subprocess tree
          command: bash -lc 'unset NODE_OPTIONS; export NODE_OPTIONS=; npx --no-install percy exec -- pnpm run cypress-run'
          publish-summary: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_E2E }}
          PERCY_TARGET_BRANCH: main
